avatar:
  size: 50
  large_size: 100
session:
  remember_value: "1"
role:
  admin: "admin"
  supervisor: "supervisor"
  trainee: "trainee"
pagination:
  size: 15
status:
  pending: 0
  started: 1
  finished: 2
